<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{73f5d705-ee79-4f84-b027-343b752c5397}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[FIS_pgr();

Test_fbFis();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="35" Count="0" />
      <LineId Id="157" Count="0" />
      <LineId Id="155" Count="0" />
      <LineId Id="158" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>