<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FuzzyNOT" Id="{17055457-a70b-4efc-a9d6-8d2632a83c74}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FuzzyNOT : REAL
VAR_INPUT
	MD:REAL;//MEMBERSHIP DEGREE
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FuzzyNOT:=1-MD;]]></ST>
    </Implementation>
    <LineIds Name="FuzzyNOT">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>