<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="fbFuzzyAnd" Id="{fb609b59-bfae-41e3-963c-299cb3a2cec7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbFuzzyAnd
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbFuzzyAnd">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>